### ISSUE TITLE
Image normalization

### ISSUE THREAD

**Issue by seann999** [johnrso/spawnnet#1]
Hi, this is not exactly about SpawnNet but I have a question regarding the MVP model.
Based on the lines below,
https://github.com/johnrso/spawnnet/blob/0edc7f0ca6003202d7085ece452ce7fb7a92bc02/simple_bc/encoder/spawnnet/spawnnet.py#L39-L48
is it correct to say that the normalization mean and std is (0.5, 0.5, 0.5) when MVP is used? Is this correct? I thought they used ImageNet values.
I ask because I'm having trouble getting MVP to work and saw that it's working decently for SpawnNet in the paper.

**Comment by Xingyu-Lin** [comment]
We follow this normalizationa after communication with the author
